// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
//const baseServiceUrl = "http://3.6.107.90:8001/";
const baseServiceUrl = "http://3.6.107.90:8001/";
const baseCustomerServiceUrl = "http://3.6.107.90:8002/";
const baseSharedServiceUrl = "http://3.6.107.90:8005/";
const baseBookingServiceUrl = "http://3.6.107.90:8003/";
const baseFSQServiceUrl = "http://3.6.107.90:8004/";

export const environment = {
  production: false,
  englishText: {
    // Asset
    AddNewAssetText: "+ Add New Asset",
    SearchText: "Search Asset By Name/Code",
    VehicleIdText: "Vehicle ID Number",
    ManufacturerText: "Manufacturer",
    ModelText: "Model",
    CodeText: "Code",
    ManufacturedateText: "Manufacture Date",
    StatusText: "Status",
    TypeText: "Type",
    ImeiText: "IMEI",
    AddAssetHeaderText: "Add Asset",
    VehicleTypeText: "Vehicle Type",
    OwnershipType: "Ownership Type",
    CustomerState: "Customer State",
    VehicleAssetCodeText: "Asset Code",
    VehicleManufacturerText: "Vehicle Manufacturer",
    VehicleModelText: "Vehicle Model",
    VehicleManufactureDateText: "Manufacture Date",
    VehicleWarrantyExpiryText: "Warranty Expiry Date",
    VehicleWarrantyTermsText: "Warranty Terms",
    VehicleQrCodeText: "QR Code",
    VehicleImeiText: "IMEI Number",
    partsDefinitionText: "Parts Definition",
    vehicletypeText: "Vehicle Type",
    addPartsDefinitionText: "Add Parts Definition",
    VehicleIdNumberText: "Vehicle ID",
    ChassisNumberText: "Chassis Number",
    insurance_no: "Insurance Policy No",
    insurance_career: "Insurance Carrier",
    insurance_upto: "Insurance Upto",
    VehicleStatusText: "Vehicle Status",
    VehicleBatteryText: "Battery",
    VehicleDeviceText: "Device",
    VehiclePartsText: "Parts",
    SelectedDevicesText: "Selected Devices",
    SelectedPartsText: "Selected Parts",
    vehicleTripInfo: "Vehicle Trip Details",
    incidentHistory: "Incident History",
    tripuuid: "Trip UUID",
    totalTripTime: "Total Trip Time",
    paidAmount: "Paid Amount",
    FranchisesharedAmount:"Franchise Shared Amount",
    discountText: "Discount",
    tripStatus: "Trip Status",
    tripStartLocationName: "Start Location",
    TripEndLocationName: "End Location",
    customerName: "Customer Name",
    tripRefNo: "Trip Ref No",
    tripStartTime: "Start Time",
    tripEndTime: "End Time",
    totalDistanceTravelled: "Total Distance Travelled By Vehicle",
    tripDistanceTravelled: "Distance Travel",
    raisedByName: "Raised By",
    reportedTime: "Reported Time",
    problemDescription: "Problem Description",
    problemStatus: "Problem Status",
    vehicleCurrentState: "Vehicle Current State",
    workItemRefNo: "Work Item Ref No",
    assignedOn: "Assigned On",
    reportedLocationLatitude: "Reported Location Latitude",
    reportedLocationLongitude: "Reported Location Longitude",
    queueType: "Queue Type",
    actionType: "Action Type",
    assignedTo: "Assigned To",
    ridingTime: "Riding Time",
    pauseTime: "Pause Time",
    totalPayable: "Total Payable",
    tripStatusName: "Trip Status",
    bookingTime: "Booking Time",
    endTimeName: "End Time",
    distanceTravelled: "Distance Travelled",
    customername: "Customer Name",
    couponcode: "Coupon Code",
    pricingPlan: "Pricing Plan",
    ontripstarttime: "Start time",
    stateName: "State Name",
    vehicleNumber: "Vehicle No",
    corporateEnabled: "Corporate Enabled",
    tripLocation: "Trip Location",
    previousButtonText: "Previous",
    nextButtonText: "Next",
    tripLocatinStartTime: "Trip Location Start Time",
    tripLocationEndTime: "Trip Location End Time",
    showButtonText: "Show",
    searchTripDetails: "Search Trip Details",
    searchIncidentHistory: "Search Incident History",
    placeholderassetName: "Select Asset Franchise Name",
    //Asset Details
    problemCodeText: "Problem Code",
    problemAreaText: "Problem Area",
    problemSeverityText: "Severity",
    VehicledetailsText: "Vehicle Details",
    VehicleidText: "Vehicle ID",
    colonText: ":",
    WarrantyExpiryText: "Warranty Expiry",
    CurrentstatusText: "Currentstatus",
    RentalpointText: "Rental Point",
    LocktimeText: "Lock Time",
    VehicledevicesText: "Vehicle Devices",
    VehiclebatteryText: "Vehicle Battery",
    VehiclepartsText: "Vehicle Parts",
    VehicleproblemsText: "Vehicle Problems",
    LastlocationsText: "Last Locations",
    vehicleType: "Vehicle Type",
    vehicleStatus: "Vehicle Status",
    triprating: "Trip Rating (Out Of 5)",
    fsqrating: "FSQ Rating (Out Of 5)",
    ownershipType: "Ownership Type",
    allOwnershipType: "All Ownership Type",
    //Accessories Header
    accessoriesHeader: "Accessories",
    //Battery Header
    batteryHeader: "Battery",
    //Add Accessories Button
    addButton: "+ Add New Accessory",
    // User
    passwordMismatch: "* Password Mismatch",
    addbutton: "+ Add New User",
    breadcrumbs: "Home > Administration > User Management",
    usermanagementHeaderText: "User Management",
    AddUserManagementHeaderText: "Add User Management",
    EditUserManagementHeaderText: "Edit User Management",
    placeHolderText: "Search User",
    userNameText: "User Name",
    firstNameText: "First Name",
    lastNameText: "Last Name",
    phoneNumberText: "Phone Number",
    emailIDText: "Email ID",
    regionText: "Region",
    selectedregionText: "Selected Region",
    roleNameText: "Role Name",
    userTypeNameText: "User Type Name",
    userNametext: "User Name",
    passwordText: "Password",
    pintext: "PIN Code",
    confirmpasswordText: "Confirm Password",
    firstnameText: "First Name",
    lastnameText: "Last Name",
    phoneNoText: "Phone Number",
    rolenameText: "Role Name",
    userStatusNameText: "User Status",
    addButtonText: "Add",
    cancelButtonText: "Cancel",
    addAnotherText: "Add Another",
    userTypeText: "User Type",
    updatedOnText: "Last Updated On",
    ShowInactiveUsersText: "Include Inactive Users",
    corporatefranchiseName: "Corporate/Franchise Name",
    // user Corporate Text
    corporateNameText: "Corporate Name",
    corporateNamePlaceHolderText: "Select Corporate Name",
    corporatefranchiseNamePlaceHolderText: "Select Corporate/Franchise Name",
    pocNameText: "POC Name",
    pocEmailText: "POC Email",
    pocPhoneText: "POC Phone",
    pocOfficeAddressText: "POC Offfice Address",
    pocDesignationText: "POC Designation",
    // End
    // Parts
    AddButton: "+ Add New Parts",
    PlaceHolderText: "Search Parts",
    vehiclePartStateText: "Status",
    warrantyPeriodText: "Warranty Period (Month)",
    addPartsText: "Add Parts",
    editPartsText: "Edit Parts",
    ShowInactivepartsText: "Include Inactive Parts",
    //Add Battery button
    addBatteryTitleText: "Add Battery",
    editBatteryTitleText: "Edit Battery",
    addBatteryText: "+ Add New Battery",
    placeholderSearchbatteryText: "Search Battery By Name/Tag",
    //Battery Table
    BatteryIDText: "Battery ID",
    BatteryTagText: "Battery Tag",
    BatteryManufacturerText: "Manufacturer",
    BatteryModelNameText: "Model Name",
    BatteryManufacturingDateText: "Manufacturing Date",
    BatteryCommissioningDateText: "Commissioning Date",
    BatteryPowerText: "Wattage",
    BatteryOriginBatteryText: "Country of Origin",
    WarrantyPeriodText: "Warranty Period (Month)",
    BatteryStatusText: "Status",
    ShowInactiveBatteryText: "Include Inactive Batteries",
    AssigneStatus: " Assignment Status",
    BatteryTransactionDetailsHeaderText: "View Battery Transaction Details",
    AssigneeTypeText: "Assignee Type",
    AssignedToText: "Assigned To",
    TransactionsButtonText: "Transactions",
    //Battery Transactions
    FromDateText: "From Date",
    ToDateText: "To Date",
    stockStatusText: "Stock Status",
    BatteryTraverseHistoryText: "Battery Traverse History",
    //Add battery page
    AddBatteryIDText: "ID",
    AddManufacturerText: "Battery Manufacturer",
    AddBatteryModelText: "Battery Model",
    AddCountryofOriginText: "Country of Origin",
    AddBatteryWattageText: "Battery Wattage",
    AddWarramtyPeriodText: "Warranty Period",
    AddBatteryStatus: "Battery Status",
    //Asset inventory Header
    assetInventoryHeaderText: "Asset & Inventory",
    assetInventoryBreadcrumbs: "Home > Administration > Asset & Inventory",
    // Add Device Header

    //Add Device Button
    addDevice: "+ Add New Device",
    // Device Text
    AddDeviceHeaderText: "Add Device",
    AddText: "Add",
    AddAnotherText: "Add Another",
    CancelText: "Cancel",
    SearchDevicePlaceholderText: "Search Device",
    DeviceIdText: "Device ID",
    DeviceMakeText: "Device Make",
    DeviceModelText: "Device Model",
    CountryOriginText: "Country Of Origin",
    DeviceImeiText: "Device IMEI",
    DeviceNameText: "Device Name",
    ManufacturingdateText: "Manufacturing Date",
    CommissioningdateText: "Commissioning Date",
    DeviceTagText: "Device Tag",
    AddDeviceStatus: "Device Status",
    deviceTypeText: "Device Type",
    DevicestatusnameText: "Status",
    ShowInactiveDeviceText: "Include Inactive Devices",
    DeviceTransactionPageHeaderText: "View Device Transaction Details",
    DeviceTraverseHistoryText: "Device Traverse History",
    // Save text
    SaveText: "Save",
    // Edit Text
    EditText: "Edit",
    // Reset Password
    resetPasswordText: "Reset Password",
    // Delete Text
    DeleteText: "Delete",
    AssignText: "Assign",

    // ActionText
    ActionText: "Action",
    // Edit Device Header Text
    EditDeviceHeaderText: "Edit Device",
    // rental point text
    rpAddButtonText: "+ Add Rental Point",
    rpPlaceholderText: "Search Rental Point",
    rpHistoryPlaceholderText: "Serch Rental Point History",
    rpHistoryText: "Rental Point History",
    VehicleInText:"Vehicle In",
    VehicleInOutText:"Vehicle In/Out",
    vehicleTypeNameText:"Vehicle Type",
    vehicleinoutText:"Vehicle In/Out",
    tripreferencenumberText:"Trip Reference Number",
    arrivaltimeText:"Arrival Time",
    VehicleOutText:"Vehicle Out",
    inouttimeText:"In/Out Time",
    departuretimeText:"Departure Time",
    // Rental point Table header
    rptableHeaderAddress: "Address",
    rptableHeaderCity: "City",
    rptableHeaderRegion: "Region",
    rptableHeaderState: "State",
    rptableHeaderCountryCode: "Country",
    rptableHeaderPostalCode: "Postal Code",
    rptableHeaderCommissioningDate: "Commissioning Date",
    rptableHeaderTerminationDate: "Termination Date",
    rptableHeaderMaximumCapacity: "Max Capacity",
    rptableHeaderAvailableCapacity: "Avl Capacity",
    rptableHeaderrentalTableStatusName: "Rental Point Status",
    rptaleHeaderType: "Type",
    rptableHeaderOpeningTime:"Opening Time",
    rptableHeaderTClosingTime:"Closing Time",
    ownership: "Ownership",
    frachiseName: "Franchise Name",
    allFranchise: "All Franchise",
    // rental point Page text
    rpText: "Rental Point",
    rpBatCumText: "Home > Administration > Rental Point",
    // Add rental Point Text
    rpTypeText: "Rental Point Type",
    placeholderRentalPointType: "Select Rental Pont Type",
    rpOwnershipCodeText: "Ownership Code",
    rpFranchiseName: "Franchise Name",
    placeholderrpFranchiseName: "Select Rental Point Franchise Name",
    fanplaceholder: "Select Franchise",
    placeholderRentalPointOwnershipCode: "Select Rental point Ownership Code",
    latText: "Latitude",
    lngText: "Longitude",
    addRentalPointText: "Add Rental Point",
    addrentalpointButtonText: "Add",
    rentalPointNameText: "Rental Point",
    addRentalPointNameText: "Rental Point Name",
    addRentalpointNamePlaceholder: "Type Rental Point Name",
    rentalPointShortCodeText: "Rental Point Short Code",
    rentalPointShortcodePlaceholder: "Type Rental Point Short Code",
    rpAddressLine1Text: "Address Line1",
    rpAddressLine1Placeholder: "Type Address Line1",
    rpAddressLine2Text: "Address Line2",
    rpAddressLine2Placeholder: "Type Address Line2",
    rpCityText: "City",
    rpCiytPlaceholderText: "Type Your City",
    rpCuntryCodeText: "Choose Country",
    rpCuntryCodePlaceHolderText: "Select Your Country",
    rpPostalCode: "Postal Code",
    rpPostalCodePlaceHolsderText: "Type Your Postal Code",
    rpMaxCapacity: "Max Capacity",
    rpMaxCapacityPlaceHolderText: "Type Your Max Capacity",
    rpAvailableCapacity: "Available Capacity",
    rpAvailableCapacityPlaceHolderText: "Type Your Available Capacity",
    rpCommissioningDate: "Commissioning Date",
    rpCommissioningDatePlaceHolder: "Choose Commissioning Date",
    rpTerminationDate: "Termination Date",
    rpTerminationDatePlaceHolder: "Choose Termination Date",
    rpStatusText: "Rental Point Status",
    rpStatusPlaceholderText: "Select Rental Point Status",
    rentalpointdetails: "Details",
    moveText: "Move",
    rpOpeningTimeText: "Opening Time",
    rpCloseTimeText: "Closing Time",
    rpHoursText: "HH",
    rpMinutesText: "MM",
    rpSecondText: "SS",
    rpMoveButtonText: "Move",
    rpMapViewText: "Map View",
    rpNameText: "Rental point Name  ",
    rpCodeText: "Rental Point Code  ",
    batteryswappingpoint: "Battery Swapping Point",
    rentalPointManagerName: "Rental Point Manager",
    rentalpointmanager: "Rental Point Manager",
    rentalPointDetails: "Rental Point Details",
    statusname: "Status Name",
    rentalPointTypeName: "Rental Point Type",
    currentParkedVehicleDetails: "Current Parked Vehicle Details",
    currentParkedVehicle: "Current Parked Vehicle",
    availableSlot: "Available Slot",
    vehicleTypeName: "Vehicle Type",
    manufacturer: "Manufacturer",
    model: "Model",
    manufacturerDate: "Manufacturer Date",
    warrantyExpiry: "Warranty Expiry",
    warrantyTerms: "Warranty Terms",
    qrcode: "QR Code",
    vehiclenumber: "Vehicle Number",
    vehicleStatusName: "Vehicle Status",
    batteryDetailText: "Battery Detail",
    stockStatustext: "Stock Status",
    // Franchise Pricing
    FranchisepricingAddButtonText:"+ Add Franchise Price",
    FranchisepricingSearchPlaceholderText:"Search Franchise Pricing",
    pricingstartrentalpointrateText:"Start Rentalpoint Cost",
    pricingstartrentalpointmaxrateText:"Start Rentalpoint Max Cost",
    pricingendrentalpointrateText:"End Rentalpoint Cost",
    pricingendrentalpointmaxrateText:"End Rentalpoint Max Cost",
    pricingvehicleownerrateText:"Vehicle Owner Cost",
    pricingvehicleownermaxrateText:"Vehicle Owner Max Cost",

    //Pricing Management
    pricingManagementHeaderText: "Pricing Management",
    pricingBreadcrumbs: "Home > Administration > Pricing",
    pricingAddButtonText: "+ Add New Pricing",
    BatterySwapPricingAddButtonText: "+ Add Battery Swap Price",
    BatterySwappricingSearchPlaceholderText: "Search Battery Swap Pricing",
    pricingSearchPlaceholderText: "Search Pricing",
    pricingTierHeader: "Tier",
    pricingNameHeader: "Name",
    pricingTierMinHeader: "Tier Min Value",
    pricingTierMaxHeader: "Tier Max Value",
    pricingUnitHeader: "Unit (Minute)",
    pricingCostHeader: "Cost / Unit",
    pricingMinAmountHeader: "Min Amount",
    pricingUnlockCostHeader: "Unlock Cost",
    pricingVehicleTypeHeader: "Vehicle Type",
    pricingRegionNameHeader: "Region Name",
    pricingActionHeader: "Action",
    pricingTierText: "Pricing Tier",
    pricingNameText: "Tier Name",
    pricingTierMinText: "Tier Min Value",
    pricingTierMaxText: "Tier Max Value",
    pricingUnitText: "Unit (Minute)",
    pricingCostText: "Cost / Unit",
    pricingTempCostText: "Temp Cost",
    pricingMinAmountText: "Min Amount",
    pricingUnlockCostText: "Unlock Cost",
    pricingVehicleTypeText: "Vehicle Type",
    pricingRegionNameText: "Region Name",
    pricingAllRegionsText: "All Regions",
    pricingAllVehicleTypesText: "All Vehicle Types",
    pricingTabletypeText: "Type",
    priceTablePartnerName: "Corporate",
    pricingtypeText: "Pricing Type",
    adminPartneridText: "Partner",
    selectPartnerText: "Select Partner",
    partnerText: "Partner",
    noofinitialswapText: "No Of Initial Swap",
    rateforinitialswapText: "Rate For Initial Swap",
    rateforconsicutiveswapText: "Rate Per Consicutive Swap",
    batteryswappricingNameText: "Display Name",
    // Dashboard
    TotalincidentText: "Incidents",
    TotalGeofenceViolation: "Geofence Violations",
    shiftStarting: "FSQ Shifts in 30 Mins",
    Emergency: "Emergency",
    atRentalPointText: "At Rental Point",
    onTripText: "On Trip",
    incidentsText: "Incidents",
    maintenanceText: "Maintenance",
    fsqUsingText: "FSQ Using",
    timeExceededText: "Time Limit Passed",
    geofenceVoilationText: "Geofence Violated",
    readyToDeployText: "Ready to Deploy",
    totalPaidText: "Paid : ",
    totalDueText: "Due",
    totalGeneratedText: "Generated",
    totalEarnedText: "Earned",
    loggedMaintenanceText: "Logged : ",
    assignedMaintenanceText: "Assigned",

    // Region Management
    regionManagementHeaderText: "Region Management",
    regionAddButtonText: "+ Add New Region",
    regionSearchPlaceholderText: "Search Region",
    regionMapViewText: "Map View",
    regionIdHeader: "ID",
    regionCodeHeader: "Code",
    regionNameHeader: "Name",
    countryNameHeader: "Country",
    stateNameHeader: "State",
    cityNameHeader: "City",
    createdOnHeader: "Created On",
    regionCodeText: "Region Code",
    countryNameText: "Country",
    stateNameText: "State",
    increaseDistanceText: "Increase Distance",
    decreaseDistanceText: "Decrease Distance",
    regionActionHeader: "Action",
    editButtonText: "Edit",
    createdOnText: "Created On",
    centerLatitudeText: "Center Latitude",
    centerLongitudeText: "Center Longitude",
    radiusText: "Radius (Meters)",
    geometricDetailsText: "Geometric Details",
    drawText: "Draw",

    // Role Management
    rolManagementHeaderText: "Role Management",
    SearchUserRoleText: "Search User Role",
    Editroletext:"Edit Role",
    Editpermissiontext:"Edit Permission",
    RolenameText:"Role Name",
    roleAddButtonText:"+ Add New Role",
    addRoleText:"Add Role",
    editRoleText:"Edit Role",
    controlelementnameText:"Controle Element Name",
    controlelementtypenameText:"Controle Element Type Name",
    permissionNameText:"Permission",
    unusedControlText:"Unused Control",
    permissionTypeText:"Permission Type",
    serlectunusedControlText:"Select Unused Control",
    selectpermissionTypeText:"Select Permission Type",
    controlelementNameText:"Control Element Name",
    userTypenameText:"User Type Name",
    unusedRolesText:"Add Role",
    selectRolePlaceHolderText:"Select Role",

    // deploy vehicle
    DeployVehicleBreadcrumbs: "Home > Administration > Deploy Vehicle",
    DeployVehicleTitle: "Deploy Vehicle",
    DeployVehiclePlaceHolderText: "Search Request",
    AddRequest: "+ Add New Request",
    AddDeployRequest: "Add Deploy Request",
    AddVehicleButton: "+ Add Vehicle",
    requestButton: "Add Request",
    rentalPointText: "Rental Point",
    rentalPointAddressText: "Rental Point Address",
    regionNameText: "Region Name",
    assignedUserNameText: "Assigned User Name",
    deploymentRequestStatusNameText: "Status",
    vehicleAssetCodeText: "Vehicle Asset Code",
    warrantyTermsText: "Warranty Terms",
    qrCodeText: "QR Code",
    vehicleCurrentStatusNameText: "Vehicle Current Status",
    modelText: "Model",
    deployedOnText: "Deployed On",

    // Corporate Management Text
    corporatemanagementHeaderText: "Corporate/Franchise Management",
    corporateManagementBreadcrumbs: "Home > Administration > Corporate Management",
    deployVehicleButtonText: "Deploy Vehicle",
    cancelrequestText: "Cancel Request",
    searchPlaceHolderText: "Search Corporate/Franchise",
    CmTableHeaderPartnerCode: "Partner Code",
    CmTableHeaderPartnerName: "Partner Name",
    CmTableHeaderContactPhone: "Contact Phone",
    CmTableHeaderCompanyName: "Company Name",
    CmTableHeaderPartnerCategoryName: "Partner Category Name",
    CmTableHeaderUpdatedBy: "Updated By",
    CmTableHeaderPartnerType: "Partner Type",
    CmAddButtonText: "+ Add New Corporate/Franchise",
    AddCorporateUserHeaderText: "Add Corporate/Franchise",
    EditCorporateUserHeaderText: "Edit Corporate/Franchise",
    corporateFormHeaderText: "Corporate/Franchise Primary Details",
    pricingFormHeaderText: "Pricing Details",
    bankDetails: "Bank Details",
    partnerTypeText: "Partner Type",
    partnerCodeText: "Partner Code",
    partnerNameText: "Partner Name",
    partnerCategoryText: "Partner Category",
    companyNameText: "Company Name",
    addressLine1Text: "Address Line 1",
    addressLine2Text: "Address Line 2",
    cityText: "City",
    postalCodeText: "Postal Code",
    contactPersonFirstnameText: "Contact Person First Name",
    contactPersonLastnameText: "Contact Person Last Name",
    contactPersonDesignationText: "Contact Person Designation",
    contactPhoneText: "Contact Phone",
    contactPersonText: "Contact Person",
    countryCodeText: "Country Code",
    countryText: "Country",
    adduserButtonText: "Add User",
    requestButtonText: "Requests",
    corporateBillingNameText: "Corporate/Franchise Billing Name",
    gstnumberText: "GST No.",
    pannumberText: "PAN No.",
    corporateSizeText: "Corporate/Franchise Size",
    corporateContractText: "Corporate/Franchise Contract",
    billingNameText: "Billing Type",
    paymentTermText: "Payment Term (Days)",
    billGenerationFrequencyText: "Bill Generation Frequency (Days)",
    minimumWalletBalanceText: "Minimum Wallet Balance",
    allPartnerType: "All Partner Type",
    accountHolderName: "Account Holder Name",
    accountNo: "Account No",
    ifscCode: "IFSC Code",
    cinNo: "CIN No",
    BankName: "Bank Name",
    BranchName: "Branch Name",
    BankAddress: "Bank Address",
    vehicle: "View Vehicle",
    ViewRp: "View Rental Point",

    //Corporate Management Request
    corporateManagementHeaderText: "Corporate Request Management",
    corporateManagementRequestBreadcrumbs: "Home > Administration > Corporate Request Management",
    FSQfirstNameText: "FSQ First Name",
    FSQphonenumberText:"Fsq Phone Number",
    FSQShiftstarttimetext:"Shift Start Time",
    FSQShiftendtimetext:"Shift End Time",
    FSQlevelNameText:" FSQ Level Name",
    FSQcreatedByText:"Created By",
    FSQShiftDurationtext:"Duration",
    FSQstatusNameText:"Shift Status",
    ShiftAsText:"Shift As",
    FsqRegionText:"Region",
    FsqRentalpointText:"Rentalpoint",
    FSQlastNameText: "FSQ Last Name",
    statusNameText: "Status Name",
    updatedByText: "Updated By",
    includePastText: "Include Past Requests",
    UpdatedOnText: "Updated On",
    adminCompanyNameText: "Company Name",
    requestedOnText: "Requested On",
    approveButtonText: "Approve",
    rejectButtonText: "Reject",
    verifyButtonText: "Verify",
    actionText: "Action",
    corporateRequestSearchPlaceholderText: "Search Corporate Request",
    corporateText: "Corporate",
    manageShift: "Manage Shifts",
    basicDetailsText: "Basic Details",

    //Coupon Management 
    couponManagementHeaderText: "Coupon Management",
    allCouponText: "All Coupon",
    usedUnusedCouponText: "Include Used Coupon",
    addCouponText: "+ Add New Coupon",
    couponSearchPlaceHolderText: "Search Coupon",
    UnusedcouponSearchPlaceHolderText: "Search Unused Coupon",
    showInactiveCouponsText: "Include Inactive Coupons",
    couponNameText: "Name",
    couponCodeText: "Code",
    couponDescriptionText: "Description",
    discountTypeText: "Discount Type",
    couponTypeText: "Coupon Type",
    usageRestrictionText: "Usage Restriction",
    valueText: "Value",
    timeText: "Time",
    startDateText: "Start Date",
    endDateText: "End Date",
    customersText: "Customers",
    addCustomersText: "Add Customers",
    typeCustomerText: "Type Customer Details",
    aleradyAssignedCustomer: "Customer already assigned or used this coupon",
    usageHistoryText: "Usage",
    customerNametext: "Customer",
    referrerNameText: "Referrer",
    referralCouponCodeText: "Coupon Code",
    couponStatusNameText: "Coupon Status",
    referralCodeRedeemedOnText: "Redeemed On",
    couponNametext: "Coupon Name",
    couponStartDateText: "Coupon Start Date",
    referrerCouponcodeText: "Referrer Coupon Code",
    referrerCouponNameText: "Referrer Coupon Name",
    referrerCouponStatusText: "Referrer Coupon Status",
    referrerCouponStartDateText: "Referrer Coupon Start Date",

    //Corporate Code Management
    corporatecodeHeaderText: "Corporate Code Management",
    codeTypeText: "Code Type",
    corporateCodeText: "Corporate Code",
    statusText: "Status",
    createdBytext: "Created By",
    createOnText: "Created On",
    updateByText: "Updated By",
    updateOnText: "Updated On",
    partnerBNameText: "Partner Name",
    addCodeText: "+ Add New Code",
    searchCodeText: "Search Corporate Code",
    //Add Corporate Code
    AddNewCorporateCodeText: "Add Corporate Code",
    EditCorporateCodeText: "Edit Corporate Code",
    AddCodeTypeText: "Code Type",
    AddCorporateCodeText: "Corporate Code",
    AddCodeStatusText: "Code Status",
    AddCreatedOnText: "Created On",
    AddUpdatedOnText: "Updated On",
    AddPartnerNameText: "Partner Name",

    //Corporate Billing
    corporateBillingHeaderText: "Corporate Billing",

    //Deploy Request Vehicle
    searchDeployRequestVehiclePlaceHolderText: "Search Deploy Request Vehicle",

    //Fsq request Management
    updateFSQManagementHeaderText: "Edit Shift Management",
    FsqManagementHeaderText: "FSQ Management",
    FsqRequestSearchPlaceHolderText: "Search FSQ Request",
    FSQText: "FSQ",
    currentAddressText: "Current Address",
    permanentAddressText: "Permanent Address",
    fsqStatusNameText: "Status",
    fsquserTypeNameText: "User Type",
    assignRegionButtonText: "Assign Region",
    fsqAssignRegion: "FSQ Assign Region",
    fsqStartTime: "Shift Start Time",
    fsqEndTime: "Shift End Time",
    FSQNameHeader: "FSQ Name",
    RegionNameHeader: "Region Name",
    fsqHubName: "Hub Name",
    fsqSkillText: "FSQ Skill Level",
    fsqGender: "Gender",
    breaktimeText:"Break Time",
    minutesText:"Minutes",

    //Fsq Request
    vehicleDetails: "Vehicle Detail",
    allocatedby: "Allocated By",
    allocatedTime: "Allocated Time",
    jobDetail: "Job Detail",
    ShiftDetail: "Shift Detail",
    bookVehicle: "Book Vehicle",
    backButton: "Back",
    fsqDetails: "FSQ Details",
    includeinactivehub: "Include Inactive Hub",


    //Report list Management
    workItemidText: "Work Item Id",
    taskText: "Task",
    IncidenttypeText: "Incident Type",
    ReportedbyCustomertypeText: "Customer Type",
    VehicletypeText: "Vehicle Status",
    vehicleNumbertext: "Vehicle Number",
    incidentNumberText: "Incident Number",
    reportedTimetext: "Reported Time",
    assignText: "Assign",
    reassignText:"Reassign",
    viewButtonText: "View",
    ReportSearchPlaceHolderText: "Search Incident Report",
    statusHeaderText: "Status",
    fsqNameText: "FSQ Name",
    // allassignText: "Allassigned",
    ShowAssignedText: "Include Assigned",
    showResolvedText:"Include Resolved",
    locationsText: "Locations",
    customerLoactionText: "Customer Location",
    fsqLocationText: "FSQ Location",
    reportLocationText: "Report Location",
    acceptJobLocationText: "Accept Job Location",
    refreshData: "Refresh Data",

    // Report Popover
    reportDetailstext: "Report details",
    searchReportDetailsText: "Search Report Details",
    ItemidText: "Item Id",
    ItemtypeText: "Item Type",
    submitText: "Submit",
    AssignFSQText: "Assign FSQ",
    TasknameText: "Task Name",
    PartNameText:"Part Name",
    PartStatusNameText:"Part Status Name",
    TasksevertyText: "Task Sevarty",
    TaskdescriptionText: "Task Description",
    TaskcreateatText: "Create At",
    TaskstatusText: "Task status",
    TaskcodeText: "Task Code",
    SelecttaskText: "Select Task",
    ProblemText: "Problems",
    //report detail popover
    TripNoText: "Trip Ref No",
    WorkItemNotext: "Work Item Ref No",
    CustomerNameText: "Customer Name",
    TripStatusText: "Trip Status",
    VehicleNumberText: "Vehicle Number",
    WorkTypeText: "Work Type",
    ReportTime: "Report Time",
    TaskDetailText: "Task Detail",
    TaskCodeText: "Task Code",
    TaskNameText: "Task Name",
    CreateAtText: "Create At",
    prrorityText: "Priority",
    FsqNameText: "FSQ Name",
    UserNmaeText: "User Name",
    ContactText: "Contact",
    AssignedTimeText: "Assigned Time",
    CustomerTypeText: "Customer Type",
    ReportedTimeText: "Reported Time",
    searchTripDetailsText: "Search Trip Details",

    //Customer Management
    customerManagementHeaderText: "Customer Management",
    customerRequestSearchPlaceHolderText: "Search Customer",
    IncludeinactiveCustomerText:"Include Inactive Customer",
    corporateCustomerfirstNameText: "First Name",
    corporateCustomerlastNameText: "Last Name",
    activeButtonText: "Activate",
    inactiveButtonText: "Deactivate",
    emailVerficationText: "Email Verification",
    corporateProfileText: "Corporate Profile",
    kycStatusText: "Kyc Status",
    dpinStatusText: "Dpin Status",
    customerCurrentStateText: "Current State",
    customertripsHeaderText: "Customer Trips",
    //Customer Details
    customerDetailsText: "Customer Details",
    txnDetailsText: "Wallet Details",
    tripDetailsText: "Trip Details",
    priceBreakupDetails: "Price Breakup Details",
    tripEvent: "Trip Event",
    tripRefNoText: "Trip Ref No",
    bookingTimeText: "Booking Time",
    vehicleText: "Vehicle",
    startRentallPointText: "Start Rental Point",
    corporateTripText: "Corporate Trip",
    couponText: "Coupon",
    endRentalPointText: "End Rental Point",
    endTimeText: "End Time",
    distanceText: "Distance",
    ridingTimeText: "Riding Time",
    pauseTimeText: "Pause Time",
    tripTimeText: "Trip Time",
    tripStatusText: "Status",
    walletBalanceText: "Balance : ",
    txnRefText: "Txn Ref",
    bankTxnText: "Bank Txn Ref",
    gatewayTxnRef: "Gateway Txn Ref",
    txnStatusText: "Status",
    txnTimeText: "Time",
    txnAmountText: "Amount",
    txnTypeText: "Txn Type",
    emergencyContactText: "Emergency Contacts",
    contactNameText: "Contact Name",

    // Trip Management
    TripManagementHeaderText: "Trip Management",
    searchTripSearchPlaceHolderText: "Search Trip",
    showOngoingPastTripText: "Include Past Trip",
    tripRefferencenoText: "Trip Reference Number",
    startLocationtext: "Start Location",
    endLocationtext: "End Location",
    OntripstartTimeText: "On-trip Start Time",
    DistancetravelledText: "Distance Travelled",
    tripStatusNametext: "Trip status",
    OntripendTimeText: "On-trip End Time",
    PaidamountText: "Paid Amount",
    endtripButtonText: "End Trip",
    tripDetails: "Details",
    endTripText: "End Trip",
    TripDetails: "Trip Details",
    eventName: "Event Name",
    eventCreated: "Event Created",
    breakupCostIemName: "Breakup Cost Item Name",
    amount: "Amount",

    // Franchise Trip Managemet
    franchiseTripManagementHeaderText: "Franchise Trip Management",
    franchiseRentalpointManagementHeaderText:"Franchise Rental Point Management",
    franchiseTripDetails: "Franchise Trip Details",

    // Franchise Pricing
    franchisePricingHeaderText:"Franchise Pricing",

    // Parameter Management
    addParameter: "+ Add New Parameter",
    SearchParameterPlaceholderText: "Search Parameter",
    parameterManagementHeaderText: "Parameter Management",
    parameterActionHeader: "Action",
    parameterKeyHeader: "Key",
    prarameterValueHeader: "Value",
    //Incident Mnagement
    incidentManagementHeaderText: "Incident Management",

    //Default Error Message
    defaultErrorMessage: "Error Encountered, Please Try Again.",

    //Header Component
    logoutButtonText: "Logout",
    profileButtonText: "Profile",
    changePasswordButtonText: "Change Password",
    profileDetails: "Profile Details",
    oldPasswordText: "Old Password",
    newPassWordText: "New Password",
    changeMobileNumberText: "Change Mobile Number",
    newMobileNoText: "New Mobile No.",
    // FSQ Hub
    FsqHubHeaderText: "FSQ Hub",
    addFSQHUB: "+ Add New FSQ Hub",
    SearchFsqHubPlaceholderText: "Search FSQ Hub",
    SearchRegionPlaceholderText: "Search Hub Region",
    SearchManagerPlaceholderText: "Search Hub Manager",
    SearchFSQPlaceholderText: "Search FSQ",
    hubShortcodeText: "Short Code",
    HubnameText: " Hub Name",
    FSQNameText: "FSQ Name",
    FSQtatusText: "FSQ Status",
    addressText: "Address",
    FSQHubregionstatusText: "Region Status",
    CreatedbyText: "Created By",
    CreatedonText: "Created On",
    AddFsqHubHeaderText: "Add FSQ Hub",
    FSQHubregionText: "Region",
    SelectedRegionsText: "Selected Regions",
    AddressLine1Text: "Address Line1",
    AddressLine2Text: "Address Line2",
    CityText: "City",
    StateText: "Choose State",
    CountryText: "Choose Country",
    PostalCode: "Postal Code",
    AddressLine1Placeholder: "Type Address Line1",
    AddressLine2Placeholder: "Type Address Line2",
    CiytPlaceholderText: "Type Your City",
    StatePlaceHolderText: "Select Your State",
    CountryPlaceHolderText: "Select Your Country",
    PostalCodePlaceHolsderText: "Type Your Postal Code",
    tableHeaderPostalCode: "Postal Code",
    tableHeaderStateText: "State",
    tableHeaderCountryText: "Country",
    tableHeaderCity: "City",
    tableHeaderAddress: "Address",
    hubDetailText: "Hub Detail",
    hubIdText: "Hub ID",
    managerText: "Manager",
    FSQHubroleText: "role",
    SelectedManagersText: "Selected Managers",
    HubuserText: "Manager Detail",
    RegiondetailText: "Region Detail",
    HubdetailText: "Hub Detail",
    FSQHubManagerstatusText: "Manager Status",
    FSQHubstatusText: "Hub Status",
    hubregionNameText: "Region Name",
    hubStartDateText: "Start Date",
    hubendDateText: "End Date",
    hubRegionstatusText: "Region Status",
    hubManagerstatusText: "Manager Status",
    hubmanagerNameText: "Manager Name",
    ShowInactiveRegionText: "Include Inactive Regions",
    ShowInactiveManagerText: "Include Inactive Managers",
    ShowInactiveFSQText: "Include Inactive FSQ",
    ClearText: "Clear",
    FSQdetailText: "FSQ Details",
    RemoveText: "Remove",
    activeManager: "Active Managers",
    //vehicle management
    ShiftStartTimeText: "Shift Start Time",
    ShiftEndTimeText: "Shift End Time",
    rentalPointCode: "Rental Point Code",

    // Customer Kyc Verification
    customerKycVerificationHeaderText:"Customer Kyc Verification",
    // Iot Bypass
    IotBypassText: "IOT BYPASS",
    SearchIotPlaceholderText: "Search Iot Bypass",
    vehicleIdText: "Vehicle Id",
    vehicleCurrentstateText: "Vehicle Current State",
    Actiontext: "Action",
    TripRefNoText: "Trip Ref No",
    MoreActionDetailsText: "More Action Details",
    CustomerStateText:"Customer State",
    TripTypeText:"Trip Type",
    corporatecodeText:"Corporate Code",
    CustomerEmailText: "Email Id",
    CustomerPhoneText: "Phone No.",
    CustomerBookingPinText: "Booking Pin",
    TripDetailText: "Trip Details",
    TripStatusNameText: "Trip Status",
    TripBookingTimeText: "Booking Time",
    TripStartTimeText: "Start Time",
    TripEndLocationText: "End Location",
    TripStartLocationText: "Start Location",
    TripuuidNoText: "Trip Uuid",
    VehicleNoText: "Vehicle No",
    VehicleTypeNameText: "Vehicle Type",
    VehicleCurrentStatusNameText: "Vehicle Current Status",
    TripStartText: "Trip Start",
    TripPauseText: "Trip Pause",
    TripResumeText: "Trip Resume",
    BookSlotText: "Book Slot",
    EndTripText: "End Trip",
    TripCurrentStateText: "Trip Current State",
    AssociateVehicleNoText: "Associate Vehicle No",
    BookingtimeText: "Booking Time",
    MoreActiontext: "More Action",
    SelectRentalPointText: "Select RentalPoint Text",
    ListofRentalPointText: "List Of RentalPoint",
    VehiclenumberText: "Vehicle Number",
    vehicleTypeText: "Vehicle Type",
    Configuretext: "Configure",
    addBypassText: "Add Bypass",
    BypassnameText: "Bypass Name",
    BypassstatusText: "Bypass Status",
    TripCancelText: "Cancel Booking",
    TokenidText: "Token Id",
    CancelSlotText: "Cancel Slot",
    OutputText: "Output",
    AddDemoDeviceText: "+ Add Demo Device",
    CalculateText: "Calculate",
    vehiclenumberText: "Vehicle Number",
    DemoDeviceStatus: "Demo Device Status",
    changeOutputText: "Change Output",
    speedText: "Speed",
    batterystatusText: "Battery Status",


    //State Tax
    stateTaxManagementText: "State Tax Management",
    addNewStateTaxButtonText: "+ Add New State Tax",
    searchStateTaxText: "Search State Tax",
    taxTypeText: "Tax Type",
    taxRateText: "Tax Rate",

    //Parts Master
    AddPartsTypeButton: "+ Add Parts Types",
    SearchPartsTypesText: "Search Parts Types",
    partNameText: "Name",
    partCodeText: "Code",
    partManufacturerText: "Manufacturer",
    partSourceCountryNameText: "Country of Origin",
    partPriceText: "Price",
    partTagText: "Tag",
    inStockText: "In Stock",
    damagedText: "Damaged",
    inUseText: "In Use",
    ownershipTypeName: "Ownership Type",
    franchise_name: "Franchise Name",
    ItemModel: "Item Model",


    //Parts Stock
    inventoryText: "Inventory",
    storeTypeText: "Store Type",
    storeNameText: "Store",
    quantityText: "Quantity",
    transactionsText: "Transactions",
    searchPartsInventoryText: "Search Parts Inventory",
    addPurchasedStock: "+ Add Purchased Stock",
    addText: "Add",
    transactionReferenceText: "Txn Reference",

    //Parts Transactions
    searchPartsTranasactionsText: "Search Parts Transactions",
    txnDateText: "Date",
    txnReferenceText: "Txn Ref",

    //Parts Transfer
    transferPartsText: "Transfer Parts",
    searchTrasnferRequestsText: "Search Transfer Requests",
    approveText: "Approve",
    rejectText: "Reject",
    transferRefText: "Transfer Ref",
    sourceRegionText: "Source Region",
    sourceStoreTypeText: "Source Store Type",
    sourceStoreText: "Source Store",
    destRegionText: "Dest Region",
    destStoreTypeText: "Dest Store Type",
    destStoreText: "Dest Store",
    sourcePartStatusText: "Source Part Status",
    destPartStatusText: "Dest Part Status",
    partsTxnStatusText: "Txn Status",
    addTransferRequestText: "+ Add Transfer Request",
    destinationDetailsText: "Destination Details",
    sourceDetailsText: "Source Details",
    partText: "Part",
    selectText: "Select",
    filterText: "Filter",
    allText: "All",
    clearText: "Clear",
    showText: "Show",
    Gettext: "Get",
    ItemText: "Item",
    Transferrefno: "Transfer Ref No",
    TransferDetailText: "Transfer Detail",
    transferDeviceBatteryText: "Transfer Battery / Device",
    //Maintenance Jobs
    maintenanceJobsText: "Maintenance",
    workItemText: "Work Item",
    workItemTypeText: "Type",
    raisedByText: "Raised By",
    roleText: "Role",
    reportTimeText: "Report Time",
    EmergencyContactText: "EmergencyContact",
    tripText: "Trip",
    underMaintenanceText: "Under Maintenance",
    searchMaintenanceJobsText: "Search Maintenance Jobs",
    daysText: " Days",
    fsqLevelText: "FSQ Level",
    workItemDetailsText: "Work Item Details",
    lastMaintenanceText: "Last Maintenance",
    daysAgoText: " Days Ago",
    maintenanceCountText: "Maintenance Count",
    travelSinceMaintenanceText: "Travel Since Maintenance",
    locationDetailsText: "Location Details",
    assignmentDetailsText: "Assignment Details",
    kmText: " KM",
    assignedFsqText: "Assigned FSQ",
    assignedOnText: "Assigned On",
    daysAssignedText: "Days Assigned",
    partsChangedText: "Parts Changed",
    resolveText: "Resolve",
    clearFilterText: "Clear Filter",
    assignmentFormText: "Assignment Form",
    createMaintenanceJobText: "+ Add Maintenance Job",
    commentsText: "Comments",
    commentText: "Comment",
    assignmentStatus: "Assignment Status",
    managingBeuText: "Managing BEU",
    ItemTag: "Item Tag",
    beuNameText: "BEU Name",
    beuPhoneText: "BEU Contact",
    fsqPhoneText: "FSQ Contact",

    // Maintenance Schedule
    updateScheduleText: "Update Schedule",
    vehicleAgeText: "Vehicle Age",
    distanceSinceLastMaintenanceText: "Distance Since Last Maintenance(KM)",
    dyasSinceLastMaintenanceText: "Days Since Last Maintenance",
    scheduleUpdatedSuccessfullyText: "Schedule Updated Successfully",

    //Problem Inventory Tagging
    problemInventoryTagHeadertext: "Problem Code Inventory Tagging",
    problemTypeText: "Problem Type",
    problemNameText: "Problem Name",
    severityNameText: "Severity Name",
    addPartText: "Add Part",
    selectPartPlaceHolderText: "Select Part",
    partNameTableHeadertText: "Part Name",

    //Search Select
    searchGenericText: "Search",
    selectFromBelowText: "Select From Below",

    //Corporate Billing
    //bill-setups-main
    billsSetupText: "Bills Setup",
    setupBillButtonText: "+ Setup New Bill",
    AllBillButtonText: "All Bills",
    CorporateNameTableHeaderText: "Corporate Name",
    LegalEntityTableHeaderText: "Legal Entity Name",
    BillingStartDateTableHeaderText: "Billing Start Date",
    viewBillButtonText: "View Bills",
    //setup-billing
    SetupBillHeaderText: "Set-up Bill",
    SelectLegalEntityText: "Select Legal Entity",
    SelectCorporateText: "Select Corporate",
    AddButtonText: "Add",
    //Corporate-billing-main
    CountryFormText: "Country",
    DaysPendingText: "Days Pending",
    CorporateText: "Corporate",
    InvoiceNoText: "Invoice #",
    LastBillAmountText: "Last Bill",
    LastPaymentReceivedText: "Last Payment",
    AmountDueText: "Due",
    UnbilledAmountText: "Current Bill",
    DueDateText: "Due Date",
    NextBillDateText: "Effective",
    JobRunDateText: "Bill Date",
    generateBillText: "Generate bill",
    excelButtonText: "Excel",
    //Corporate-bill-details
    OrganizationDetailsHeaderText: "Organization Details",
    CorporateDetailsHeaderText: "Corporate Details",
    CorporateTripDetailsHeaderText: "Corporate Trip Details",
    BasicBillDetailsHeaderText: "Basic Bill Details",
    AmountText: "Amount",
    RideIdText: "Ride ID",
    RiderNameText: "Rider Name",
    BookingTimeText: "Booking time",
    RideEndTimeText: "Ride End Time",
    BasicText: "Basic",
    CgstText: "CGST",
    SgstText: "SGST",
    TotalPayableText: "Total Payable",
    DueDateTExt: "Due Date",
    AdjustmenttableHeaderText: "Additional Items/Adjustments",
    BankAccountDetailsHeaderText: "Dabadigo Bank Account Details",
    AccountHeolderText: "Account Holder",
    BankNameText: "Bank Name",
    BranchNameText: "Branch Name",
    BranchAddressText: "Branch Address",
    AccountNoText: "Account No.",
    IfscCodeText: "Ifsc Code",
    SendReminderButtonText: "Send Reminder",
    DispatchBillButtonText: "Email",
    GeneratPdfText: "PDF",
    phoneText: "Phone",
    contactEmailText: "Contact Email",
    billingHeaderText: "Billing Header",
    billToText: "Bill To",
    addNewAdjustmentButtonText: "+ Add New Adjustment",
    tripReferanceNoText: "Trip Referance No.",
    riderName: "Rider Name",
    descriptionText: "Description",
    amountPayableText: "Amount Payable",
    amountText: "Amount",
    BillPaidText: "Bill Paid",
    //Send email page
    SendemailHeaderText: "Send Email",
    SubjectText: "Subject",
    BodyText: "Body",
    NotesText: "Notes",
    saveandSendButtonText: "Save & Send",
    reminderTableHeaderText: "List of Reminders",
    reminderDateColumnHeaderText: "Reminder Date",
    reminderNotesColumnHeaderText: "Reminder Notes",
    //Franchisee Billing
    franchiseeBillingPageHeaderText: "Franchisee Billing",
    franchisetext: "Franchise",
    franchiseNameText: "Franchise Name",
    netPayableText: "Net Payable",
    AllPaymentsText: "All payment",
    PaymentSetupText: "Payment Setup",
    FranchiseeBillingNameText: "Franchisee Billing Name",
    paymentStartDate: "Payment Start Date",
    selectFranchiseeText: "Select Franchisee",
    viewPaymentDetailsHeaderText: "Payment Details For",
    paymentDetailsText: "Payment Details",
    paymentRefNoText: "Payment Ref No.",
    currentBillDateText: "Current Bill Date",
    nextBillDate: "Next Bill Date",
    amountPayable: "Amount Payable",
    franchiseDtailsSectionHeaderText: "Franchise Details",
    addresLine1Text: "Address Line 1",
    addresLine2Text: "Address Line 2",
    stateText: "State",
    pinText: "PIN",
    gstText: "GST",
    panText: "PAN",
    contactPersonNameText: "Contact Person",
    designationText: "Designation",
    emailText: "E-mail",
    franchisePaymentsSectionHeader: "Franchise Payments",
    entryDateText: "Entry Date",
    vehicleNoText: "Vehicle No.",
    rentalType: "Rental Type",
    amountPayabletext: "Amount Payable",
    addNewPenaltyButtonText: "+ Add New Penalty",
    descriptionsText: "Descriptions",
    actionsText: "Actions",
    penaltiesText: "Penalty",
    tripdatetext: "Trip Date",
  },

  urls: {
    //Login URL
    LoginURL: baseServiceUrl + "dabadigo/admin/loginuser/",
    firsttimepasswordchangeURL: baseServiceUrl + "dabadigo/admin/firsttimeloginchangepassword/",
    userForgetPassword: baseServiceUrl + "dabadigo/admin/forgetpassword/",
    //Administration URL
    AdminListURL: baseServiceUrl + "dabadigo/admin/get/allusers/",
    ActiveBEUUrl: baseServiceUrl + "dabadigo/admin/get/activebeu/",
    AdminCreateURL: baseServiceUrl + "dabadigo/admin/create/",
    GetRoleName: baseServiceUrl + "dabadigo/admin/get/applicableroles/",
    EditUserById: baseServiceUrl + "dabadigo/admin/get/users/",
    EditUser: baseServiceUrl + "dabadigo/admin/update/",
    DeleteUser: baseServiceUrl + "dabadigo/admin/delete/users/",
    resetpasswordurl: baseServiceUrl + "dabadigo/admin/resetpassword/",
    DuplicateUser: baseServiceUrl + "dabadigo/admin/check/duplicateuser/",
    //Accessories List
    AccessoryListURL: baseServiceUrl + "dabadigo/admin/get/accessories/",
    CreateAccessoryListURL: baseServiceUrl + "dabadigo/admin/create/accessories/",
    UpdateAccessoryListURL: baseServiceUrl + "dabadigo/admin/update/accessories/",
    //Parts List
    PartsListURL: baseServiceUrl + "dabadigo/admin/get/parts/",
    VehiclePartStatesURL: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",
    CreatePartsURL: baseServiceUrl + "dabadigo/admin/create/parts/",
    UpdatePartsURL: baseServiceUrl + "dabadigo/admin/update/parts/",
    EditPartById: baseServiceUrl + "dabadigo/admin/get/partsbyid/",
    deletePartUrl: baseServiceUrl + "dabadigo/admin/delete/parts/",
    DuplicateParts: baseServiceUrl + "dabadigo/admin/check/duplicatepart/",

    //Parts Master Urls
    partsMasterListUrl: baseServiceUrl + "dabadigo/admin/partsmaster/get/",
    partsMasterWithStockListUrl: baseServiceUrl + "dabadigo/admin/partsmaster/getwithstock/",
    singlePartsMasterUrl: baseServiceUrl + "dabadigo/admin/partsmaster/getbyid/",
    partsMasterCreateUrl: baseServiceUrl + "dabadigo/admin/partsmaster/create/",
    partsMasterCheckDuplicateUrl: baseServiceUrl + "dabadigo/admin/partsmaster/checkduplicate/",
    partsMasterCheckDuplicateCodeUrl: baseServiceUrl + "dabadigo/admin/partsmaster/checkduplicatecode/",
    partsMasterUpdateUrl: baseServiceUrl + "dabadigo/admin/partsmaster/update/",
    partsMasterDeleteUrl: baseServiceUrl + "dabadigo/admin/partsmaster/delete/",
    partsStockFilteredUrl: baseServiceUrl + "dabadigo/admin/partsstock/getfiltered/",
    partsTrasnactionsUrl: baseServiceUrl + "dabadigo/admin/partsstock/gettransactions/",
    addPartsStockUrl: baseServiceUrl + "dabadigo/admin/partsstock/add/",

    //Country List
    CountryLoadURL: baseSharedServiceUrl + "dabadigo/shared/get/countries/",
    //Battery List
    BatteryListURL: baseServiceUrl + "dabadigo/admin/get/batteries/",
    CreateBatteryURL: baseServiceUrl + "dabadigo/admin/create/batteries/",
    GetBatterybyIDURL: baseServiceUrl + "dabadigo/admin/get/batteriesbyid/",
    updateBatteryURL: baseServiceUrl + "dabadigo/admin/update/batteries/",
    DeleteBatteryURL: baseServiceUrl + "dabadigo/admin/delete/batteries/",
    BatteryStatusURL: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",
    DuplicateBatteryTagURL: baseServiceUrl + "dabadigo/admin/check/duplicatebattery/",
    GetBatteryTransactionsUrl: baseServiceUrl + "dabadigo/admin/history/battery/",
    //Device List
    DeviceListURL: baseServiceUrl + "dabadigo/admin/device/get/",
    AssociateDeviceListURL: baseServiceUrl + "dabadigo/admin/device/associate/",
    UpdateDeviceAllocationURL: baseServiceUrl + "dabadigo/admin/device/updateassociation/",
    DeviceStatusURL: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",
    AddDeviceListURL: baseServiceUrl + "dabadigo/admin/device/create/",
    EditDeviceLoadURL: baseServiceUrl + "dabadigo/admin/device/getbyid/",
    EditDeviceURL: baseServiceUrl + "dabadigo/admin/device/update/",
    GetCountriesURL: baseSharedServiceUrl + "dabadigo/shared/get/countries/",
    DeleteDeviceURL: baseServiceUrl + "dabadigo/admin/device/delete/",
    DuplicateDevice: baseServiceUrl + "dabadigo/admin/check/duplicatedevice/",
    DuplicateImeiNumber: baseServiceUrl + "dabadigo/admin/check/duplicatedeviceimei/",
    GetDeviceTransactionsUrl: baseServiceUrl + "dabadigo/admin/device/stockhistory/",
    // Asset Urls
    AssetListURL: baseServiceUrl + "dabadigo/admin/vehicle/get/",
    EditAssetLoadUrl: baseServiceUrl + "dabadigo/admin/vehicle/getbyid/",
    AddAssetURL: baseServiceUrl + "dabadigo/admin/vehicle/create/",
    AvailablePartsUrl: baseServiceUrl + "dabadigo/admin/available/parts/",
    AvailableBatteriesUrl: baseServiceUrl + "dabadigo/admin/available/batteries/",
    AvailableDevicesUrl: baseServiceUrl + "dabadigo/admin/device/available/",
    UpdateAssetsURL: baseServiceUrl + "dabadigo/admin/vehicle/update/",
    DuplicateAsset: baseServiceUrl + "dabadigo/admin/check/duplicateassetcode/",
    DuplicateVehicleID: baseServiceUrl + "dabadigo/admin/check/duplicatevehicle/",
    GetAssetDetailByIdUrl: baseServiceUrl + "dabadigo/admin/vehicle/getdetailbyid/",
    getPartsDefinitionByVehicleTypeUrl: baseServiceUrl + "dabadigo/admin/partsdefinition/getbyvehicletype/",
    updatePartsDefinitionUrl: baseServiceUrl + "dabadigo/admin/partsdefinition/update/",
    // Vehicle URLS
    GetVehicleByRequestListURL: baseServiceUrl + "dabadigo/admin/deploymentrequest/get/",
    GetDeployVehicleListURL: baseServiceUrl + "dabadigo/admin/vehicle/readytodeploy/",
    CreateRequestVehicleURL: baseServiceUrl + "dabadigo/admin/deploymentrequest/create/",
    DeployVehicleByIDURL: baseServiceUrl + "dabadigo/admin/deploymentrequest/getbyid/",
    UpdateDeployVehicleURL: baseServiceUrl + "dabadigo/admin/deploymentrequest/update/",
    DeleteDepoyVehicleURL: baseServiceUrl + "dabadigo/admin/deploymentrequest/delete/",

    // Get All Rental Point
    RentalPointURL: baseServiceUrl + "dabadigo/admin/get/allrentalpoints/",

    //Rentalpoint
    AddRentalPointUrl: baseServiceUrl + "dabadigo/admin/create/rentalpoint/",
    deleteRentalPointUrl: baseServiceUrl + "dabadigo/admin/delete/rentalpoint/",
    editRentalPointByIdUrl: baseServiceUrl + "dabadigo/admin/get/rentalpointsbyid/",
    editRentalPoint: baseServiceUrl + "dabadigo/admin/update/rentalpoint/",
    moveRentalPointUrl: baseServiceUrl + "dabadigo/admin/move/rentalpoint/",
    rentalPointHistory: baseServiceUrl + "dabadigo/admin/history/rentalpoint/",
    duplicateRpUrl: baseServiceUrl + "dabadigo/admin/check/duplicaterentalpoint/",
    batterySwapPointsByRegion: baseServiceUrl + "dabadigo/admin/rentalpoint/getbatteryswapbyregion/",
    GetAvailableBattery: baseServiceUrl + "dabadigo/admin/available/batteries/",
    AddBatteryRpUrl: baseServiceUrl + "dabadigo/admin/battery/deploy/ ",
    removeBatteryUrl: baseServiceUrl + "dabadigo/admin/battery/revoke/",
    RentalpointsByRegion: baseServiceUrl + "dabadigo/admin/rentalpoint/getbyregion/",
    getRegionbyCityUrl: baseServiceUrl + "dabadigo/admin/region/bycity/",
    AvailableFranchiseUrl: baseServiceUrl + "dabadigo/admin/rentalpoint/gatallfranchise/",
    taskDetailsListUrl: baseServiceUrl + "dabadigo/admin/get/partsbytaskid/",

    //FSQ URL
    getFSQListUrl: baseServiceUrl + "dabadigo/admin/fsq/getfsq/",
    FSQListUrl: baseServiceUrl + "dabadigo/admin/fsq/hubmanager/fsqrequests/",
    getActiveFsqListUrl: baseServiceUrl + "dabadigo/admin/fsq/get/activefsq/",
    fsqApproveRequestUrl: baseServiceUrl + "dabadigo/admin/fsq/approverequest/",
    getWorkItemListUrl: baseServiceUrl + "dabadigo/admin/get/incidents/",
    getSingleWorkItemUrl: baseServiceUrl + "dabadigo/admin/get/incident/byworkitem/",
    submitRequestURL: baseServiceUrl + "dabadigo/admin/assign/workitem/",
    activeFSQUrl: baseServiceUrl + "dabadigo/admin/fsq/activefsq/",
    inactiveFSQUrl: baseServiceUrl + "dabadigo/admin/fsq/inactivefsq/",
    regionByIDUrl: baseServiceUrl + "dabadigo/admin/fsqUserbyid/",
    updateRegionUrl: baseServiceUrl + "dabadigo/admin/fsq/updateregion/",
    documentVerificationUrl: baseServiceUrl + "dabadigo/admin/fsquserbyid/",
    CreateFsqShift: baseServiceUrl + "dabadigo/admin/fsq/createfsqshift/",
    GetAllShiftUrl: baseServiceUrl + "dabadigo/admin/fsq/getallshift/",
    EditShiftById: baseServiceUrl + "dabadigo/admin/fsq/getshiftbyid/",
    DeleteFSQShiftUrl: baseServiceUrl + "dabadigo/admin/fsq/deleteshift/",
    UpdateShiftURL: baseServiceUrl + "dabadigo/admin/fsq/updatefsqshift/",
    FSQActiveInactiveUrl: baseServiceUrl + "dabadigo/admin/fsq/activate/",
    GetFsqHub: baseServiceUrl + "dabadigo/admin/fsq/getallactivefsqhub/",
    EditFsqHubLevel: baseServiceUrl + "dabadigo/admin/fsq/updatefsq/",
    SearchActiveFsqUrl: baseServiceUrl + "dabadigo/admin/fsq/search/",
    GetbreakpointURL: baseServiceUrl + "dabadigo/admin/parameter/getvaluebysinglekey/",

    // FSQ Hub URL
    getFSQHubListUrl: baseServiceUrl + "dabadigo/admin/fsq/getallfsqhub/",
    getFSQ: baseServiceUrl + "dabadigo/admin/fsq/hubmanageraccess/",
    DuplicateHubcode: baseServiceUrl + "dabadigo/admin/fsq/duplicatefsqhubshortcode/",
    getManagerList: baseServiceUrl + "dabadigo/admin/fsq/getallmanager/",
    AddFSQHubURL: baseServiceUrl + "dabadigo/admin/fsq/createfsqhub/",
    getregionList: baseServiceUrl + "dabadigo/admin/fsq/getallavailableregion/",
    EditHubLoadUrl: baseServiceUrl + "dabadigo/admin/fsq/fsqhubbyid/",
    UpdateFSQHubURL: baseServiceUrl + "dabadigo/admin/fsq/updatefsqhub/",
    RemoveRegionURL: baseServiceUrl + "dabadigo/admin/fsq/removeregion/",
    RemoveManagerURL: baseServiceUrl + "dabadigo/admin/fsq/removemanager/",
    getFsqTagedRegionUrl: baseServiceUrl + "dabadigo/admin/fsq/fsqassociateregion/",

    // Iot Controller URL
    getActionmainListUrl: baseServiceUrl + "dabadigo/admin/iotbypass/getallactivetrip/",
    GetMoreActionDetailsUrl: baseServiceUrl + "dabadigo/admin/iotbypass/gettripdetails/",
    cancelTripUrl: baseBookingServiceUrl + "dabadigo/vehicle/cancelbooking/",
    startTripUrl: baseBookingServiceUrl + "dabadigo/vehicle/validatedpin/",
    PauseRideUrl: baseBookingServiceUrl + "dabadigo/vehicle/pausetrip/",
    ResumeRideUrl: baseBookingServiceUrl + "dabadigo/vehicle/resumetrip/",
    GetSlotUrl: baseServiceUrl + "dabadigo/admin/get/rentalpointsslot/",
    SlotBooking: baseBookingServiceUrl + "dabadigo/vehicle/slotrequest/",
    cancelSlotUrl: baseBookingServiceUrl + "dabadigo/vehicle/slotrequest/cancel/",
    EndTripUrl: baseBookingServiceUrl + "dabadigo/vehicle/endtrip/",
    getActiveDeviceListUrl: baseServiceUrl + "dabadigo/admin/iotbypass/getavailablevehicle/",
    GetBypassDetailsUrl: baseServiceUrl + "dabadigo/admin/iotbypass/vehiclebypasslist/",
    addBypassUrl: baseServiceUrl + "dabadigo/admin/iotbypass/addbypass/",
    getDemoDeviceListUrl: baseServiceUrl + "dabadigo/admin/iotbypass/getdummyimei/",
    DemoDeviceStatusURL: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",
    AddDemoDeviceListURL: baseServiceUrl + "dabadigo/admin/iotbypass/createdummydevice/",
    EditDemoDeviceListURL: baseServiceUrl + "dabadigo/admin/iotbypass/modifydevice/",
    getByIdDemoDeviceURL: baseServiceUrl + "dabadigo/admin/iotbypass/getdummydevicebyimei/",

    //Customer Management URL
    getCustomerUrl: baseServiceUrl + "dabadigo/admin/user/getallcustomer/",
    activeUrl: baseServiceUrl + "dabadigo/admin/user/activecustomer/",
    inactiveUrl: baseServiceUrl + "dabadigo/admin/user/inactivecustomer/",
    singleCustomerDetailUrl: baseServiceUrl + "dabadigo/admin/user/getcustomerdetail/",
    searchCustomerUrl: baseServiceUrl + "dabadigo/admin/customer/search/",
    //Customer Kyc Verification 
    customerKycdocdetailslUrl: baseCustomerServiceUrl + "dabadigo/customer/kyc/docdetails/",
    ApproveRequestUrl: baseCustomerServiceUrl + "dabadigo/customer/update/kycstatus/",
    //Fsq Vehicle management
    FsqGetRentalPoint: baseServiceUrl + "dabadigo/admin/fsq/rentalpoints/byshiftregion/",
    GetVehicleByRentalPoint: baseServiceUrl + "dabadigo/admin/fsq/vehicles/byrentalpoint/",
    BookVehicleUrl: baseServiceUrl + "dabadigo/admin/fsq/assignvehicle/",
    getAssignVehicleUrl: baseServiceUrl + "dabadigo/admin/fsq/shiftvehicle/",
    FSQStartShiftUrl: baseFSQServiceUrl + "dabadigo/fsq/start/shift/",
    FsqPauseShiftUrl: baseFSQServiceUrl + "dabadigo/fsq/pauseshift/",
    FsqResumeShiftUrl: baseFSQServiceUrl + "dabadigo/fsq/resumeshift/",
    FsqEndShiftUrl: baseFSQServiceUrl + "dabadigo/fsq/endshift/",
    FsqStartJob: baseFSQServiceUrl + "dabadigo/fsq/startwork/",
    FsqReturnVehicleUrl: baseServiceUrl + "dabadigo/admin/fsq/returnvehicle/",
    GetReturnRegionUrl: baseServiceUrl + "dabadigo/admin/fsq/regions/",
    GetReturnRPUrl: baseServiceUrl + "dabadigo/admin/fsq/rentalpointbyregion/",



    // map myindia
    // grantType:  "client_credentials",
    // clientId:  "vec63Bxf4JyAgEedeRgCDaBG4y12dvT9lA99VXgDqMZ9o5yUvx5SSTMD0ujiS6K1YFwFTf4cnHdm0wUvADAscQ==",
    // clientSecret:  "9K_q_9Q2GHPBrtLJ1GRYXM9bHQcf12H-Xr1WgBnNwldjpK28IT6Uei9Vxddt15w4oMwQHL9hVqzaelLA0rTbjr9EJBscJRhH",
    // securityURL:  "https://outpost.mapmyindia.com/api/security/oauth/token?grant_type=",
    // autoSuggestURL:  "https://atlas.mapmyindia.com/api/places/search/json?query=agra&location=28.5454,77.455454&bridge&explain&username=balmukand",
    // nearbyURL:  "https://atlas.mapmyindia.com/api/places/nearby/json?explain&richData&username=balmukand&refLocation=28.467470,77.077518&keywords=FINATM",
    // reverseGeocodingUrl: "http://apis.mapmyindia.com/advancedmaps/v1/tp9wjxu9i1h11kbgklhcgdk6azjvpvku/rev_geocode?lat=",

    //Domain Urls
    GetUserTypeURL: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",
    DomainLookupUrl: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",


    //Pricing Management
    pricingListUrl: baseServiceUrl + "dabadigo/admin/pricetable/get/",
    pricingAddUrl: baseServiceUrl + "dabadigo/admin/pricetable/create/",
    pricingEditUrl: baseServiceUrl + "dabadigo/admin/pricetable/update/",
    pricingDeleteUrl: baseServiceUrl + "dabadigo/admin/pricetable/delete/",
    singlePricingUrl: baseServiceUrl + "dabadigo/admin/pricetable/getbyid/",

    // Battery Swap Pricing Management
    batteryswappricingListUrl: baseServiceUrl + "dabadigo/admin/batteryswappricetable/get/",
    batteryswappricingAddUrl: baseServiceUrl + "dabadigo/admin/batteryswappricetable/create/",
    singlebatteryswapPricingUrl: baseServiceUrl + "dabadigo/admin/batteryswappricetable/getbyid/",
    batteryswappricingEditUrl: baseServiceUrl + "dabadigo/admin/batteryswappricetable/update/",
    batteryswappricingDeleteUrl: baseServiceUrl + "dabadigo/admin/batteryswappricetable/delete/",

    //Region
    getRegionList: baseServiceUrl + "dabadigo/admin/region/get/",
    regionaddUrl: baseServiceUrl + "dabadigo/admin/region/create/",
    singleRegionUrl: baseServiceUrl + "dabadigo/admin/region/getbyid/",
    regionEditUrl: baseServiceUrl + "dabadigo/admin/region/update/",
    GetStatesURL: baseSharedServiceUrl + "dabadigo/shared/get/states/",
    DuplicateRegion: baseServiceUrl + "dabadigo/admin/check/duplicateregion/",
    getCitiesUrl: baseSharedServiceUrl + "dabadigo/shared/get/city/",

    // Role Management
    getRoleList: baseServiceUrl + "dabadigo/admin/roles/get/",
    AddRoleURL: baseServiceUrl + "dabadigo/admin/roles/create/",
    singleRoleUrl: baseServiceUrl + "dabadigo/admin/roles/getbyid/",
    roleEditUrl: baseServiceUrl + "dabadigo/admin/roles/update/",
    getPermissionListUrl: baseServiceUrl + "dabadigo/admin/rolepermission/getuserrolepermission/",
    updatePermissionUrl: baseServiceUrl + "dabadigo/admin/rolepermission/modifypermission/",
    getUserTypeListUrl: baseServiceUrl + "dabadigo/admin/roles/getusertyperole/",
    updateUserTypeUrl: baseServiceUrl + "dabadigo/admin/roles/modifyrole/",

    // corporate URL
    getCorporateUrl: baseServiceUrl + "dabadigo/admin/corporate/get/",
    getCorporateByIdUrl: baseServiceUrl + "dabadigo/admin/corporate/getbyid/",
    editCorporateUrl: baseServiceUrl + "dabadigo/admin/corporate/update/",
    createCorporateURL: baseServiceUrl + "dabadigo/admin/corporate/create/",
    DuplicatePartnerCodeURL: baseServiceUrl + "dabadigo/admin/check/duplicatepartnercode/",

    //Corporate Code Management
    getCorporateCodeUrl: baseServiceUrl + "dabadigo/admin/corporatecode/get/",
    createCorporateCodeUrl: baseServiceUrl + "dabadigo/admin/corporatecode/create/",
    getByIdCorporateCodeUrl: baseServiceUrl + "dabadigo/admin/corporatecode/getbyid/",
    updateCorporateCodeUrl: baseServiceUrl + "dabadigo/admin/corporatecode/update/",
    deleteCorporateCodeUrl: baseServiceUrl + "dabadigo/admin/corporatecode/delete/",
    checkDuplicateCorporateCode: baseServiceUrl + "dabadigo/admin/check/duplicatecorporatecode/",

    //Coupon Management
    getCouponsUrl: baseServiceUrl + "dabadigo/admin/coupons/getallcoupons/",
    createCouponsUrl: baseServiceUrl + "dabadigo/admin/coupons/create/",
    getCouponsByIdUrl: baseServiceUrl + "dabadigo/admin/coupons/bycouponid/",
    updateCouponsUrl: baseServiceUrl + "dabadigo/admin/coupons/update/",
    deleteCoupon: baseServiceUrl + "dabadigo/admin/coupons/delete/",
    duplicateCouponCodeUrl: baseServiceUrl + "dabadigo/admin/coupons/checkduplicate/",
    assignCouponUrl: baseServiceUrl + "dabadigo/admin/coupons/assigntocustomer/",
    getUserListUrl: baseServiceUrl + "dabadigo/admin/coupons/getuserlist/",
    getUsageHistoryUrl: baseServiceUrl + "dabadigo/admin/coupons/usagehistory/",
    getReferralListUrl: baseServiceUrl + "dabadigo/admin/referrals/get/",

    //Corporate Request URL
    getCorporateRequestURL: baseServiceUrl + "dabadigo/admin/corporate/pendingrequests/",
    approveRequestURL: baseServiceUrl + "dabadigo/admin/corporate/approverequest/",
    rejectRequestUrl: baseServiceUrl + "dabadigo/admin/corporate/rejectrequest/",
    getCorporateRequestDetailURL: baseServiceUrl + "dabadigo/admin/corporate/requestdetail/",

    //Dashboard URL
    pollingDataUrl: baseServiceUrl + "dabadigo/admin/vehicle/getpositions/",

    // Trip Management
    getTripListUrl: baseServiceUrl + "dabadigo/admin/get/tripmanagement/",
    getRentalPointListUrl: baseServiceUrl + "dabadigo/admin/get/rentalpointsslot/",
    getLatLonUrl: baseServiceUrl + "dabadigo/admin/get/trip/lastlocation/",
    EndTripURL: baseServiceUrl + "dabadigo/admin/vehicle/endtrip/",
    tripdetailsURL: baseServiceUrl + "dabadigo/admin/get/customertripdetails/",

    //Profile Management URL
    createPassword: baseServiceUrl + "dabadigo/admin/changeuserpassword/",
    changeMobileNumberUrl: baseServiceUrl + "dabadigo/admin/changeuserphone/",

    // Parameter Management
    parameterListUrl: baseServiceUrl + "dabadigo/admin/parameter/get/",
    DuplicateParameter: baseServiceUrl + "dabadigo/admin/parameter/checkduplicate/",
    AddParameterURL: baseServiceUrl + "dabadigo/admin/parameter/create/",
    singleParameterUrl: baseServiceUrl + "dabadigo/admin/parameter/getbyid/",
    parameterEditUrl: baseServiceUrl + "dabadigo/admin/parameter/update/",

    //Error Framework Url
    GetErrorFrameworkUrl: baseSharedServiceUrl + "dabadigo/shared/errorframework/get/",

    //State Tax Management
    getAllStateTaxesUrl: baseServiceUrl + "dabadigo/admin/statetax/get/",
    getSingleStateTaxUrl: baseServiceUrl + "dabadigo/admin/statetax/getbyid/",
    getStateTaxesByStateUrl: baseServiceUrl + "dabadigo/admin/statetax/getbystate/",
    createStateTaxUrl: baseServiceUrl + "dabadigo/admin/statetax/create/",
    updateStateTaxUrl: baseServiceUrl + "dabadigo/admin/statetax/update/",
    deleteStateTaxUrl: baseServiceUrl + "dabadigo/admin/statetax/delete/",

    //Parts transfer urls
    getTransferRequestsUrl: baseServiceUrl + "dabadigo/admin/partstransfers/get/",
    createTransferRequestUrl: baseServiceUrl + "dabadigo/admin/partstransfers/create/",
    approveTransferRequestUrl: baseServiceUrl + "dabadigo/admin/partstransfers/approve/",
    rejectTransferRequestUrl: baseServiceUrl + "dabadigo/admin/partstransfers/reject/",
    deleteTransferRequestUrl: baseServiceUrl + "dabadigo/admin/partstransfers/delete/",
    //Battery And  Device Urls
    GetItemLoadUrl: baseServiceUrl + "dabadigo/admin/transfer/itemlist/",
    CreateBatteryAndDeviceTransferRquest: baseServiceUrl + "dabadigo/admin/transfer/create/",
    GetAllTransferRequestListUrl: baseServiceUrl + "dabadigo/admin/transfer/get/ ",
    GetSingleTransferRequestListUrl: baseServiceUrl + "dabadigo/admin/transfer/getdetails/",
    MultiTransferUrl: baseServiceUrl + "dabadigo/admin/transfer/actions/",
    //Incident Management
    GetIncidentDetailUrl: baseServiceUrl + "dabadigo/admin/get/incident/workitemdetails/",
    //Maintenance Jobs Urls
    getMaintenanceJobsUrl: baseServiceUrl + "dabadigo/admin/maintenancejobs/get/",
    getMaintenanceJobsFilteredUrl: baseServiceUrl + "dabadigo/admin/maintenancejobs/getfiltered/",
    getMaintenanceJobsByIdUrl: baseServiceUrl + "dabadigo/admin/maintenancejobs/getbyid/",
    assignMaintenanceJobUrl: baseServiceUrl + 'dabadigo/admin/maintenancejobs/assign/',
    createMaintenanceJobUrl: baseServiceUrl + 'dabadigo/admin/maintenancejobs/create/',
    resolveMaintenanceJobUrl: baseServiceUrl + 'dabadigo/admin/maintenancejobs/resolve/',

    //Maintenance Schedule Urls
    getScheduleByVehicleTypeUrl: baseServiceUrl + 'dabadigo/admin/maintenanceschedule/getbyvehicletype/',
    updateMaintenanceScheduleUrl: baseServiceUrl + 'dabadigo/admin/maintenanceschedule/update/',

    //Problem Code Tagging
    GetProblemByCode: baseServiceUrl + "dabadigo/admin/problems/getbycode/",
    GetAllProblems: baseServiceUrl + "dabadigo/admin/problems/get/",
    updateProblemInventoryTagging: baseServiceUrl + "dabadigo/admin/problems/modifyparts/",

    //Corporate Billing
    GetCorporateBills: baseServiceUrl + "dabadigo/admin/billing/getbillbycorporateid/",
    GetLegalEntities: baseServiceUrl + "dabadigo/admin/billing/getlegalentities/",
    GetAllCorporates: baseServiceUrl + "dabadigo/admin/billing/getcorporates/",
    GetAllBillSetups: baseServiceUrl + "dabadigo/admin/billing/getsetups/",
    CreateSetup: baseServiceUrl + "dabadigo/admin/billing/createsetup/",
    GetorganizationDetails: baseServiceUrl + "dabadigo/admin/billing/getlegalentitiesbyid/",
    GetCorporateDetails: baseServiceUrl + "dabadigo/admin/billing/getorganizationbyid/",
    GetBillDetails: baseServiceUrl + "dabadigo/admin/billing/getbilldetailsbyid/",
    filterCorporateBillsUrl: baseServiceUrl + "dabadigo/admin/billing/filtercorporatebills/",
    generatePDFUrl: baseServiceUrl + "dabadigo/admin/billing/billpdfgenerate/",
    sendEmailUrl: baseServiceUrl + "dabadigo/admin/billing/sendemail/",
    sendEmailLoad: baseServiceUrl + "dabadigo/admin/billing/sendmaildetails/",
    GenerateAdjustment: baseServiceUrl + "dabadigo/admin/billing/generateadjustment/",
    BillPaymentUrl: baseServiceUrl + "dabadigo/admin/billing/billpaid/",
    //Dashboard
    dashboardPollingUrl: baseServiceUrl + "dabadigo/admin/dashboard/get/",
    //Terms and Conditions
    getTermsandConditionsUrl: baseServiceUrl + "dabadigo/admin/parameter/gettandc/",
    addTermsandConditionsUrl: baseServiceUrl + "dabadigo/admin/parameter/createtandc/",
    updateTermsandConditionsLoadURL: baseServiceUrl + "dabadigo/admin/parameter/gettandcbyid/",
    updateTermsandConditions: baseServiceUrl + "dabadigo/admin/parameter/updatetandc/",
    //Franchise rentalpoint
    FranchiseRentalPointUrl: baseServiceUrl + "dabadigo/admin/get/franchisepoints/",
    FranchiserentalPointHistory: baseServiceUrl + "dabadigo/admin/history/franchiserp/",
    //Franchise Vehicle
    FranchiseVehicleUrl: baseServiceUrl + "dabadigo/admin/vehicle/franchiseget/",
    // Franchise pricing
    getfranchisepricingListUrl: baseServiceUrl + "dabadigo/admin/franchise/getpricetable/",
    
    //Franchisee billing
    getFranchiseeSetupUrl: baseServiceUrl + "dabadigo/admin/franchise/getsetup/",
    addFranchiseeLoadUrl: baseServiceUrl + "dabadigo/admin/franchise/getfranchise/",
    addFranchiseeUrl: baseServiceUrl + "dabadigo/admin/franchise/createsetup/",
    FilterPayments: baseServiceUrl + "dabadigo/admin/franchise/getpayments/",
    ViewPaymentDetailsUrl: baseServiceUrl + "dabadigo/admin/franchise/getdetailsbyid/",
    AddPenaltyUrl: baseServiceUrl + "dabadigo/admin/franchise/createpenalty/",
    FranchiseePaymentStatusUrl: baseSharedServiceUrl + "dabadigo/shared/domainlookup/bydomaintype/",
    FranchiseePaymentAcknowledgeUrl: baseServiceUrl + "dabadigo/admin/franchise/paid/",
  },

  sidenavItems: [
    {
      headerIcon: "administration-icon",
      headerText: "Administration",
      open: false,
      menuItems: [
        {
          control: "user_management",
          menuLink: "/user-management",
          menuText: "User Management",
          permission: 0,
        },
        {
          control: "asset_inventory",
          menuLink: "/asset-inventory",
          menuText: "Asset & Inventory",
          permission: 0,
        },
        {
          control: "rental_point_management",
          menuLink: "/rental-point",
          menuText: "Rental Point Management",
          permission: 0,
        },
        {
          control: "deploy_vehicle",
          menuLink: "/deploy-vehicle",
          menuText: "Deploy Vehicle",
          permission: 0,
        },
        {
          control: 'transfer_parts',
          menuLink: "/transfer-parts",
          menuText: "Transfer Parts",
          permission: 0
        },
        {
          control: 'transfer_device_battery',
          menuLink: "/transfer-device-battery",
          menuText: "Transfer Device + Battery",
          permission: 0
        },
        {
          control: "region_management",
          menuLink: "/region-management",
          menuText: "Region Management",
          permission: 0,
        },
        {
          control: "parameter_management",
          menuLink: "/parameter-management",
          menuText: "Parameter Management",
          permission: 0,
        },
        {
          control: "iot_bypass",
          menuLink: "/iot-controller-bypass",
          menuText: "Controller Bypass",
          permission: 0
        },
        {
          control: "role_management",
          menuLink: "/role-management",
          menuText: "Role Management",
          permission: 0,
        },
        {
          control: "franchise_asset",
          menuLink: "/franchise-management-asset",
          menuText: "Franchise Vehicle",
          permission: 0,
        },
        {
          control: "franchise_rental_point",
          menuLink: "/franchise-rental-point",
          menuText: "Franchise Rental Point",
          permission: 0,
        },
      ]
    },
    {
      headerIcon: "partner-management-icon",
      headerText: "Partner Management",
      open: false,
      menuItems: [
        {
          control: "corporate_management",
          menuLink: "/corporate-management",
          menuText: "Corporate/Franchise Management",
          permission: 0,
        },
        {
          control: "corporate_code_management",
          menuLink: "/corporate-code-management",
          menuText: "Corporate Code Management",
          permission: 0,
        },
        {
          control: "corporate_request_management",
          menuLink: "/corporate-request-management",
          menuText: "Corporate Request Management",
          permission: 0,
        },
        {
          control: "corporate_billing",
          menuLink: "/corporate-billing",
          menuText: "Corporate Billing",
          permission: 0,
        },
        {
          control: "franchisee_billing",
          menuLink: "/franchisee-billing",
          menuText: "Franchisee Billing",
          permission: 0
        },
        {
          control: "corporate_bills",
          menuLink: "/corporate-bills",
          menuText: "Corporate Bills",
          permission: 0,
        },
        {
          control: "franchisee_bills",
          menuLink: "/franchisee-bills",
          menuText: "Franchisee Bills",
          permission: 0
        },
      ]
    },
    {
      headerIcon: "business-administration-icon",
      headerText: "Business Administration",
      open: false,
      menuItems: [
        {
          control: "fsq_management",
          menuLink: "/fsq-request-management",
          menuText: "FSQ Management",
          permission: 0,
        },
        {
          control: "admin_fsq_hub",
          menuLink: "/admin-fsq-hub",
          menuText: "Admin FSQ Hub",
          permission: 0,
        },
        {
          control: "fsq_hub",
          menuLink: "/fsq-hub",
          menuText: "FSQ Hub",
          permission: 0,
        },
        {
          control: "pricing_management",
          menuLink: "/pricing-management",
          menuText: "Pricing Management",
          permission: 0,
        },
        {
          control: "state_tax",
          menuLink: "/state-tax",
          menuText: "State Tax Management",
          permission: 0,
        },
        {
          control: "coupon_management",
          menuLink: "/coupon-management",
          menuText: "Coupon Management",
          permission: 0,
        },
        {
          control: "incident_management",
          menuLink: "/incident-management",
          menuText: "Incident Management",
          permission: 0,
        },
        {
          control: "maintenance_jobs",
          menuLink: "/maintenance-jobs",
          menuText: "Maintenance",
          permission: 0,
        },
        {
          control: "trip_management",
          menuLink: "/trip-management",
          menuText: "Trip Management",
          permission: 0,
        },
        {
          control: "franchise_trip_management",
          menuLink: "/franchise-management-trip",
          menuText: "Franchise Trip Management",
          permission: 0,
        },
        {
          control: "franchise_pricing",
          menuLink: "/franchise-pricing",
          menuText: "Franchise Pricing",
          permission: 0,
        },
        {
          control: "customer_management",
          menuLink: "/customer-management",
          menuText: "Customer Management",
          permission: 0,
        },
        {
          control: "customer_kyc_verification",
          menuLink: "/customer-kyc-verification",
          menuText: "Customer Kyc Verification",
          permission: 0,
        },
        {
          control: "problem_inventory_tagging",
          menuLink: "/problem-inventory-tagging",
          menuText: "Problem Inventory Tagging",
          permission: 0,
        },
        {
          control: "terms_and_conditions",
          menuLink: "/terms-and-conditions",
          menuText: "Terms and Conditions",
          permission: 0,
        }
      ]
    }
  ]
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
